version: "3.7"
name: crm
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    container_name: mariadb-crm
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-crm
    restart: unless-stopped

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8079:8000
      - 9000:9000
    container_name: frappe-crm
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
