version: "3.7"
name: crm
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    container_name: mariadb-crm
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-crm
    restart: unless-stopped

  frappe:
    image: frappe/bench:latest
    command: >
      bash -c "
      if [ -f /workspace/init.sh ]; then
        chmod +x /workspace/init.sh && bash /workspace/init.sh
      else
        echo 'init.sh not found, creating inline script...'
        cat > /tmp/init.sh << 'EOF'
        #!/bin/bash
        # Wait for MariaDB to be ready
        echo 'Waiting for MariaDB to be ready...'
        while ! mysqladmin ping -h'mariadb' -P'3306' --silent; do
          sleep 2
        done
        echo 'MariaDB is ready!'
        
        # Wait for Redis to be ready
        echo 'Waiting for Redis to be ready...'
        while ! redis-cli -h redis ping > /dev/null 2>&1; do
          sleep 2
        done
        echo 'Redis is ready!'
        
        if [ -d '/home/frappe/frappe-bench/apps/frappe' ]; then
          echo 'Bench already exists, starting services...'
          cd frappe-bench
          bench start
        else
          echo 'Creating new bench...'
          bench init --skip-redis-config-generation frappe-bench --version version-15
          cd frappe-bench
          bench set-mariadb-host mariadb
          bench set-redis-cache-host redis://redis:6379
          bench set-redis-queue-host redis://redis:6379
          bench set-redis-socketio-host redis://redis:6379
          sed -i '/redis/d' ./Procfile
          sed -i '/watch/d' ./Procfile
          bench get-app crm --branch main
          bench new-site crm.localhost --force --mariadb-root-password 123 --admin-password admin --no-mariadb-socket
          bench --site crm.localhost install-app crm
          bench --site crm.localhost set-config developer_mode 1
          bench --site crm.localhost set-config mute_emails 1
          bench --site crm.localhost set-config server_script_enabled 1
          bench --site crm.localhost clear-cache
          bench use crm.localhost
          echo 'Bench setup completed successfully!'
        fi
        echo 'Starting Frappe bench...'
        bench start
        EOF
        chmod +x /tmp/init.sh && bash /tmp/init.sh
      fi
      "
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8079:8000
      - 9000:9000
    container_name: frappe-crm
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
